//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEquipment()
        {
            this.tbScan = new HashSet<tbScan>();
        }
    
        public int e_id { get; set; }
        public string e_nameA { get; set; }
        public string e_name { get; set; }
        public string e_type { get; set; }
        public string e_note { get; set; }
        public string e_description { get; set; }
        public string e_location { get; set; }
        public System.DateTime date_in { get; set; }
        public string e_contact { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbScan> tbScan { get; set; }
    }
}
