//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFile
    {
        public int f_id { get; set; }
        public string f_path { get; set; }
        public int f_pid { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string f_name { get; set; }
        public string f_table { get; set; }
        public string f_author { get; set; }
        public Nullable<int> f_filetype { get; set; }
        public string f_md5 { get; set; }
        public int open_status { get; set; }
        public int f_fpid { get; set; }
        public int sp_id { get; set; }
        public int ref_id { get; set; }
        public System.DateTime date_up { get; set; }
        public int f_count { get; set; }
    }
}
