//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRef
    {
        public int ref_id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public int year { get; set; }
        public string cite { get; set; }
        public string url { get; set; }
        public string doc { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    }
}
