//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbScan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbScan()
        {
            this.tbSlice = new HashSet<tbSlice>();
        }
    
        public int scan_id { get; set; }
        public int e_id { get; set; }
        public int sp_id { get; set; }
        public int scan_tag_SpecimenAlive { get; set; }
        public string scan_operator { get; set; }
        public System.DateTime scan_timebegin { get; set; }
        public Nullable<System.DateTime> scan_timeend { get; set; }
        public string scan_para_SourceType { get; set; }
        public string scan_para_Camera { get; set; }
        public Nullable<double> scan_para_SourceVoltage { get; set; }
        public Nullable<double> scan_para_SourceCurrent { get; set; }
        public string scan_para_CameraBinning { get; set; }
        public int scan_para_FilesNumber { get; set; }
        public string scan_para_ImageFomat { get; set; }
        public Nullable<double> scan_para_ImagePixelSize { get; set; }
        public Nullable<double> scan_para_Object2Source { get; set; }
        public Nullable<double> scan_para_Camera2Source { get; set; }
        public Nullable<double> scan_para_VerticalObjectPosition { get; set; }
        public Nullable<double> scan_para_Exposure { get; set; }
        public Nullable<double> scan_para_RotationStep { get; set; }
        public Nullable<double> scan_para_LensMultiple { get; set; }
        public System.DateTime date_in { get; set; }
        public int open_status { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string scan_source_save_path { get; set; }
        public Nullable<double> scan_para_SourcePower { get; set; }
        public string scan_specimen_Body { get; set; }
        public string Abstract { get; set; }
        public int ref_id { get; set; }
        public Nullable<double> scan_para_PixelSize { get; set; }
    
        public virtual tbEquipment tbEquipment { get; set; }
        public virtual tbSpecimen tbSpecimen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSlice> tbSlice { get; set; }
    }
}
