//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSlice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSlice()
        {
            this.tbLabel = new HashSet<tbLabel>();
        }
    
        public int slice_id { get; set; }
        public int scan_id { get; set; }
        public string slice_para_ReconstructionProgram { get; set; }
        public string slice_para_ResultFileType { get; set; }
        public Nullable<double> slice_para_PixelSize { get; set; }
        public Nullable<int> slice_para_SliceNumber { get; set; }
        public int open_status { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public string slice_save_path { get; set; }
        public string slice_para_CutMethod { get; set; }
        public string Abstract { get; set; }
        public int sp_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLabel> tbLabel { get; set; }
        public virtual tbScan tbScan { get; set; }
    }
}
