//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSpecies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSpecies()
        {
            this.tbSpecimen = new HashSet<tbSpecimen>();
        }
    
        public int species_id { get; set; }
        public string species_latin { get; set; }
        public string species_Order { get; set; }
        public string species_Family { get; set; }
        public string species_Genus { get; set; }
        public string species_Species { get; set; }
        public string species_CHN { get; set; }
        public string species_note { get; set; }
        public string species_LSID { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSpecimen> tbSpecimen { get; set; }
    }
}
