//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSpecimen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSpecimen()
        {
            this.tbScan = new HashSet<tbScan>();
        }
    
        public int sp_id { get; set; }
        public Nullable<int> species_id { get; set; }
        public string sp_note { get; set; }
        public System.DateTime date_in { get; set; }
        public string sp_collector { get; set; }
        public string sp_collect_time { get; set; }
        public string sp_collect_place { get; set; }
        public string sp_spid { get; set; }
        public string sp_dehydrant { get; set; }
        public string sp_dryinstrument { get; set; }
        public Nullable<int> sp_drycirletime { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> specimen_sex { get; set; }
        public string specimen_age { get; set; }
        public string specimen_dry_save_path { get; set; }
        public string Abstract { get; set; }
        public string sp_preserve_status { get; set; }
        public int ref_id { get; set; }
        public string sp_identifier { get; set; }
    
        public virtual tbSpecies tbSpecies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbScan> tbScan { get; set; }
    }
}
