//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTag
    {
        public int tag_id { get; set; }
        public string tag_tag { get; set; }
        public string tag_tagCN { get; set; }
        public string tag_note { get; set; }
        public System.DateTime date_in { get; set; }
        public Nullable<int> tag_type { get; set; }
        public Nullable<int> tag_pid { get; set; }
    }
}
