//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public Nullable<System.DateTime> date_up { get; set; }
    }
}
