//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vQuick
    {
        public int slice_id { get; set; }
        public Nullable<int> scan_id { get; set; }
        public Nullable<int> sp_id { get; set; }
        public Nullable<int> slice_para_SliceNumber { get; set; }
        public string e_nameA { get; set; }
        public string species_note { get; set; }
        public string species_Order { get; set; }
        public string sp_spid { get; set; }
        public string sp_note { get; set; }
        public Nullable<System.DateTime> scan_timebegin { get; set; }
        public string sp_dehydrant { get; set; }
        public Nullable<int> sp_drycirletime { get; set; }
        public string sp_collector { get; set; }
        public string sp_time { get; set; }
        public string sp_place { get; set; }
        public Nullable<int> specimen_sex { get; set; }
        public string specimen_age { get; set; }
        public string scan_specimen_Body { get; set; }
        public string scan_para_CameraBinning { get; set; }
        public Nullable<double> scan_para_SourceVoltage { get; set; }
        public Nullable<double> scan_para_SourceCurrent { get; set; }
        public Nullable<double> scan_para_Exposure { get; set; }
        public string specimen_dry_save_path { get; set; }
        public string scan_source_save_path { get; set; }
        public string slice_save_path { get; set; }
        public Nullable<int> e_id { get; set; }
    }
}
